project:

  type: website

  output-dir: docs

 

website:

  title: "Behrokh ML Blog Project"

  repo-url: https://github.com/Behrokhb/ML-Blog-project-

  repo-actions: [edit, issue]

  navbar:

    right:

      - about.qmd

     
format:

  html:

    theme: quartz

    css: styles.css
